info:
  contact: {}
  license:
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Babel Book Library API
  version: "1.0"
paths:
  /books/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Get book by id
swagger: "2.0"
